// Real Tortuguitas team data (from agustinmarquez-dev/dashboard-tortuguitas)
window.TORTU_DATA = {
  brand: {
    name: "Tortuguitas",
    eyebrow: "Equipo de Selección",
    sub: "Sabores Express · Hamburguesas Extremas",
  },
  user: {
    name: "Agustín Marquez",
    role: "Coordinador adjunto",
    initials: "AM",
    hue: 220,
  },
  totals: { zonales: 43, locales: 193, referentes: 5 },
  kpis: [
    {
      id: "entrevistas",
      label: "Entrevistas hoy",
      value: 14,
      delta: "+12%",
      deltaDir: "up",
      compare: "vs ayer",
      accent: "blue",
      icon: "users",
      spark: [4, 6, 5, 7, 6, 9, 8, 11, 10, 13, 12, 14],
    },
    {
      id: "avanzados",
      label: "Candidatos avanzados",
      value: 8,
      delta: "+8%",
      deltaDir: "up",
      compare: "vs ayer",
      accent: "cyan",
      icon: "check",
      spark: [2, 3, 3, 4, 5, 4, 6, 5, 7, 6, 8, 8],
    },
    {
      id: "cierre",
      label: "Tasa de cierre semanal",
      value: "92%",
      delta: "+5%",
      deltaDir: "up",
      compare: "vs semana pasada",
      accent: "violet",
      icon: "star",
      spark: [70, 74, 78, 80, 82, 85, 87, 86, 88, 90, 91, 92],
    },
    {
      id: "pendientes",
      label: "Pendientes",
      value: 3,
      delta: "-10%",
      deltaDir: "down",
      compare: "vs ayer",
      accent: "amber",
      icon: "clock",
      spark: [8, 7, 9, 6, 7, 5, 6, 4, 5, 4, 3, 3],
    },
  ],
  team: [
    {
      id: "kevin",
      name: "Kevin García",
      role: "Coordinador general",
      tag: "Visionario",
      hue: 220,
      stats: [
        { label: "Equipo", value: 5 },
        { label: "Zonales", value: 43 },
        { label: "% Op.", value: "98%" },
      ],
      progress: 98,
      online: true,
    },
    {
      id: "emiliano",
      name: "Emiliano",
      role: "Altas Icheck & Soporte",
      tag: "Genuino",
      hue: 160,
      stats: [
        { label: "Altas", value: 312 },
        { label: "Soportes", value: 87 },
        { label: "% SLA", value: "96%" },
      ],
      progress: 96,
      online: true,
    },
    {
      id: "agustina",
      name: "Agustina Castillo",
      role: "Garantía & Resolución",
      tag: "Incondicional",
      hue: 290,
      stats: [
        { label: "Casos", value: 15 },
        { label: "Resueltos", value: 14 },
        { label: "% Éxito", value: "93%" },
      ],
      progress: 93,
      online: true,
    },
    {
      id: "agustin",
      name: "Agustín Marquez",
      role: "Garantía & Resolución",
      tag: "Perfeccionista",
      hue: 25,
      stats: [
        { label: "Casos", value: 14 },
        { label: "Resueltos", value: 13 },
        { label: "% Éxito", value: "92%" },
      ],
      progress: 92,
      online: true,
    },
    {
      id: "mariano",
      name: "Mariano Nussbaum",
      role: "Garantía & Resolución",
      tag: "Potencial",
      hue: 50,
      stats: [
        { label: "Casos", value: 14 },
        { label: "Resueltos", value: 12 },
        { label: "% Éxito", value: "86%" },
      ],
      progress: 86,
      online: false,
    },
  ],
  weekly: {
    series: [18, 22, 19, 26, 24, 14, 9], // entrevistas por día
    days: ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"],
  },
  weekly2: {
    series: [11, 14, 12, 17, 15, 8, 5], // cierres
  },
  proximas: [
    { time: "20:00", name: "Sofía Gómez", role: "Entrevista inicial — Zona Norte", day: "Hoy", hue: 220 },
    { time: "21:30", name: "Martín López", role: "Entrevista inicial — Zona Sur", day: "Hoy", hue: 160 },
    { time: "10:00", name: "Valentina Ruiz", role: "Entrevista final — Capital", day: "Mañana", hue: 290 },
    { time: "12:15", name: "Tomás Aguirre", role: "Segunda entrevista — Oeste", day: "Mañana", hue: 25 },
  ],
  tareasUrgentes: [
    { title: "Seguimiento a Julián Pérez", due: "Vence en 2h", level: "danger" },
    { title: "Entrevista con Sofía Gómez", due: "Hoy 20:00 hs", level: "warning" },
    { title: "Enviar propuesta a M. Rodríguez", due: "Vence mañana", level: "info" },
    { title: "Cerrar onboarding Zona Norte", due: "Vence mañana", level: "info" },
  ],
  actividad: [
    { who: "Agustín Marquez", what: "Avanzó a Juan Pérez", when: "hace 15 min", hue: 25 },
    { who: "Agustina Castillo", what: "Completó entrevista con Ana López", when: "hace 1 h", hue: 290 },
    { who: "Mariano Nussbaum", what: "Respondió seguimiento de Pedro Díaz", when: "hace 2 h", hue: 50 },
    { who: "Emiliano", what: "Cargó 8 altas Icheck — Zona Sur", when: "hace 3 h", hue: 160 },
    { who: "Kevin García", what: "Aprobó cierre mensual abril", when: "hace 4 h", hue: 220 },
  ],
  accesos: [
    { id: "entrev", label: "Nueva entrevista", icon: "plus", href: "#nueva", accent: "blue" },
    { id: "seg", label: "Seguimiento rápido", icon: "flash", href: "#seg", accent: "cyan" },
    { id: "rep", label: "Reporte diario", icon: "doc", href: "#rep", accent: "violet" },
    { id: "horarios", label: "Horarios equipo", icon: "clock", href: "pages/horarios-equipo.html", accent: "amber" },
  ],
  herramientas: [
    { label: "Cierres de mes 2026", desc: "Tablero anual de cierres", href: "pages/cierres-de-mes-2026.html" },
    { label: "Cierre mensual", desc: "Reporte del mes en curso", href: "pages/cierre-mensual.html" },
    { label: "Stack interno", desc: "Documentación y procesos", href: "pages/stack.html" },
    { label: "Horarios del equipo", desc: "Agenda compartida", href: "pages/horarios-equipo.html" },
    { label: "Zonales", desc: "Distribución y cobertura", href: "pages/zonales.html" },
    { label: "Capacitaciones", desc: "Linktree formación", href: "https://linktr.ee/capacitaciones_seleccion" },
  ],
};
